### ISSUE TITLE
What version of StarRocks does this work with?

### ISSUE THREAD

**Issue by alberttwong** [mklzl/starrocks_ansible#12]
I'm curious.  Also if it's still maintained, I'd like to publicize it to the StarRocks community.

**Comment by mklzl** [comment]
sorry ,thank you for your interest in this project. this warehouse will not continue to be maintained, if you have any questions, you can continue to discuss

**Comment by alberttwong** [comment]
too bad because StarRocks won another award yesterday. https://atwong.medium.com/starrocks-wins-infoworlds-2023-bossie-award-for-best-open-source-software-0ecaec87a784
